### PR TITLE
Mark as dead because we do not maintain this component at all

### PR DESCRIPTION
**Pull request by JakeChampion**
Let's be honest, we don't support this component at all and should archive it. If someone wants a carousel component, let's make an o-carousel component for that instead of having to rebuild o-gallery in it's entirety

### CODE REVIEW

**Comment by origamiserviceuser** [comment]
o-gallery bundle size difference from 4.0.8 to 73e6e56ee9d09ddd288f02912c020582bbedd404
No significant bundle size differences found.

**Comment by notlee** [comment]
We should advertise that it's pending deprecation in the support slack channel, it might still be used by the commercial design team. There's a proposal for a similar carousel component https://github.com/Financial-Times/origami/issues/23

**Comment by JakeChampion** [comment]
I've posted in the support channel about the decommissioning of this component -- https://financialtimes.slack.com/archives/C02FU5ARJ/p1606132713196000

**Review by chee — APPROVED** [review]

**Comment by origamiserviceuser** [comment]
:tada: This PR is included in version v4.0.9 :tada:

**Pull request merged**
