### PR TITLE
[Do Not Merge] Add/Modify/Remove files for housekeeping

### PR DESCRIPTION
**Pull request by j-mes**
**Don't merge this. It still has a few failing issues with OBT test.**

# Housekeeping

**origami.json changes**
- Add settings from config.json
- Check for correct support link
- Change from Travis to Circle CI

**README.md changes**
- Add shield on README.md for Circle CI

**Add / Remove files**
- Add circle.yml
- Remove travis.yml
- Remove html files inside `demos/`
- Remove config.json from `demos/src/`

**JavaScript files**
- Remove `"use strict";`
- Change to either `let` or `const` from `var`

**Tests**
- Passed OBT verify check
- Passed OBT demo check

### CODE REVIEW

**Comment by onishiweb** [comment]
Tests are failing because of the switch over to Webpack in the karma config. Will need to go through this with someone to work out what our options are.

**Comment by alicebartlett** [comment]
What's the status with this? @onishiweb

**Comment by onishiweb** [comment]
Something about the switch to using `let` and `const` is causing issues with either the tests or the actual JS functions, I'm not entirely sure which. I spent some time looking into it already, but I'll give it another hour today to see if I can find the issue.

**Comment by onishiweb** [comment]
Closed because the ES6 updates were breaking the tests.

**Pull request closed without merging**
