### PR TITLE
Remove old demos, switch to circle CI, and update Readme/origami config

### PR DESCRIPTION
**Pull request by onishiweb**

### CODE REVIEW

**Comment by onishiweb** [comment]
@j-mes let me know if there's anything I've missed.

**Comment by AlbertoElias** [comment]
It can't pass verify with es5 code though, right?

**Comment by onishiweb** [comment]
Oh yes, good point. I tested that `obt test` worked, but not verify. Shall I remove that from the circle config for now?

**Comment by j-mes** [comment]
I would presume that it'll complain about ES5 code yes, as it will advocate for the removal of strict mode since ES6 has it on by default as an example.

**Comment by AlbertoElias** [comment]
Yeah, remove it from the config

**Comment by onishiweb** [comment]
Ok, testing again. Should hopefully pass this time.

**Comment by onishiweb** [comment]
Yay, circle is passing!

**Comment by j-mes** [comment]
:+1:

**Comment by AlbertoElias** [comment]
Good to go!

On Mon, 6 Jun 2016 at 15:54 James Loveridge <notifications@github.com>
wrote:

> 👍
>
> —
> You are receiving this because you were assigned.
> Reply to this email directly, view it on GitHub
> <https://github.com/Financial-Times/o-gallery/pull/57#issuecomment-223983806>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AA3u3S4lfCuWWv2K4G7x395R6D_EAv1gks5qJDTDgaJpZM4Iu8FG>
> .
>

-- 

------------------------------

*This email was sent by a company owned by Financial Times Group Limited 
("FT Group <http://aboutus.ft.com/corporate-information/#axzz3rajCSIAt>"), 
registered office at Number One Southwark Bridge, London SE1 9HL.  
Registered in England and Wales with company number 879531. This e-mail may 
contain confidential information. If you are not the intended recipient, 
please notify the sender immediately, delete all copies and do not 
distribute it further.  It could also contain personal views which are not 
necessarily those of the FT Group.  We may monitor outgoing or 
incoming emails as permitted by law.*

**Pull request merged**
